from .admin_serializer import AdminSerializer
from .content_serializer import ContentSerializer
from .feedback_serializer import FeedbackSerializer
from .user_serializer import UserSerializer
from .favorites_serializer import Favourites
# from .dashboard_settings_serializer import DashboardSettingsSerializer
from .likes_serializer import LikesSerializer
from .collaborations_serializer import Collaborations
from .chatbot_serializer import ChatbotSerializer
from .chatmsg_serializer import ChatMsgSerializer